"""Placeholder for _chump C extension module.

This module will be implemented as a C extension for the chump package manager.
Currently not available - this file exists only for type checking purposes.

At runtime, importing this module raises ImportError to maintain the same
behavior as when the C extension is not built.
"""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    # Type stubs for static analysis

    class ChumpManager:
        """Package manager interface."""

        def __init__(
            self, chuck_version: str, api_version: int, api_revision: int
        ) -> None: ...
        def list_packages(self) -> list[Any]: ...
        def get_package(self, name: str) -> Any | None: ...
        def install(self, package_spec: str) -> bool: ...
        def uninstall(self, name: str, force: bool) -> bool: ...
        def update(self, name: str) -> bool: ...
        def update_manifest(self) -> bool: ...
        def is_installed(self, name: str) -> bool: ...
        def install_path(self, name: str) -> str: ...
        def packages_dir(self) -> str: ...
        def chuck_version(self) -> str: ...

    def packages_dir() -> str: ...
    def which_os() -> str: ...
    def which_arch() -> str: ...

else:
    # Runtime: raise ImportError to indicate extension not available
    raise ImportError(
        "_chump C extension not available. "
        "Package management features require the chump extension to be built."
    )
