"""Type stubs for numchuck module."""

from typing import Callable, Dict, List, Tuple, Any, TypedDict
import numpy as np
from numpy.typing import NDArray

class AudioMeters(TypedDict):
    """Audio meter values from get_audio_meters()."""

    rms_left: float
    rms_right: float
    peak_left: float
    peak_right: float

# ChucK class
class ChucK:
    """ChucK virtual machine and compiler."""

    def __init__(self) -> None: ...

    # Initialization
    def init(self) -> bool: ...
    def start(self) -> bool: ...

    # Parameters
    def set_param(self, name: str, value: int) -> None: ...
    def set_param_float(self, name: str, value: float) -> None: ...
    def set_param_string(self, name: str, value: str) -> None: ...
    def set_param_string_list(self, name: str, value: List[str]) -> None: ...
    def get_param_int(self, name: str) -> int: ...
    def get_param_float(self, name: str) -> float: ...
    def get_param_string(self, name: str) -> str: ...
    def get_param_string_list(self, name: str) -> List[str]: ...

    # Compilation
    def compile_code(
        self,
        code: str,
        args: str = "",
        count: int = 1,
        immediate: bool = False,
        filepath: str = "",
    ) -> Tuple[bool, List[int]]: ...
    def compile_file(
        self, path: str, args: str = "", count: int = 1, immediate: bool = False
    ) -> Tuple[bool, List[int]]: ...

    # Audio processing
    def run(
        self, input: NDArray[np.float32], output: NDArray[np.float32], num_frames: int
    ) -> None: ...

    # Global variables - primitives
    def set_global_int(self, name: str, value: int) -> None: ...
    def set_global_float(self, name: str, value: float) -> None: ...
    def set_global_string(self, name: str, value: str) -> None: ...
    def get_global_int(self, name: str, callback: Callable[[int], None]) -> None: ...
    def get_global_float(
        self, name: str, callback: Callable[[float], None]
    ) -> None: ...
    def get_global_string(self, name: str, callback: Callable[[str], None]) -> None: ...

    # Global variables - arrays
    def set_global_int_array(self, name: str, values: List[int]) -> None: ...
    def set_global_float_array(self, name: str, values: List[float]) -> None: ...
    def set_global_int_array_value(self, name: str, index: int, value: int) -> None: ...
    def set_global_associative_int_array_value(
        self, name: str, key: str, value: int
    ) -> None: ...
    def get_global_int_array(
        self, name: str, callback: Callable[[List[int]], None]
    ) -> None: ...
    def get_global_float_array(
        self, name: str, callback: Callable[[List[float]], None]
    ) -> None: ...

    # Global events
    def signal_global_event(self, name: str) -> None: ...
    def broadcast_global_event(self, name: str) -> None: ...
    def listen_for_global_event(
        self, name: str, callback: Callable[[], None], listen_forever: bool = True
    ) -> int: ...
    def stop_listening_for_global_event(self, name: str, callback_id: int) -> None: ...

    # Introspection
    def get_all_globals(self) -> List[Tuple[str, str]]: ...

    # Shred management
    def remove_shred(self, shred_id: int) -> None: ...
    def remove_all_shreds(self) -> None: ...
    def replace_shred(self, shred_id: int, code: str, args: str = "") -> int: ...
    def get_all_shred_ids(self) -> List[int]: ...
    def get_shred_info(self, shred_id: int) -> Dict[str, Any]: ...

    # VM control
    def clear_vm(self) -> None: ...
    def reset_shred_id(self) -> None: ...
    def clear_globals(self) -> None: ...

    # Lifecycle
    def shutdown(self) -> None: ...

    # Status
    def is_init(self) -> bool: ...
    def vm_running(self) -> bool: ...
    def now(self) -> float: ...

    # Display
    def toggle_global_color_textoutput(self, onOff: bool) -> None: ...

    # Chugins
    def probe_chugins(self) -> None: ...

    # Callbacks
    def set_chout_callback(self, callback: Callable[[str], None] | None) -> bool: ...
    def set_cherr_callback(self, callback: Callable[[str], None] | None) -> bool: ...

    # Static methods
    @staticmethod
    def version() -> str: ...
    @staticmethod
    def int_size() -> int: ...
    @staticmethod
    def num_vms() -> int: ...
    @staticmethod
    def set_log_level(level: int) -> None: ...
    @staticmethod
    def get_log_level() -> int: ...
    @staticmethod
    def global_cleanup() -> None: ...
    @staticmethod
    def poop() -> None: ...
    @staticmethod
    def set_stdout_callback(callback: Callable[[str], None] | None) -> bool: ...
    @staticmethod
    def set_stderr_callback(callback: Callable[[str], None] | None) -> bool: ...
    @staticmethod
    def create(sample_rate: int, channels: int) -> ChucK: ...

# Module-level functions
def version() -> str: ...
def start_audio(
    chuck: ChucK,
    sample_rate: int = 44100,
    num_dac_channels: int = 2,
    num_adc_channels: int = 0,
    dac_device: int = 0,
    adc_device: int = 0,
    buffer_size: int = 512,
    num_buffers: int = 8,
) -> bool: ...
def stop_audio() -> bool: ...
def shutdown_audio(msWait: int = 0) -> None: ...
def audio_info() -> Dict[str, int]: ...
def is_audio_running() -> bool: ...
def get_audio_meters() -> AudioMeters: ...

# Parameter constants
PARAM_AUTO_DEPEND: str
PARAM_CHUGIN_ENABLE: str
PARAM_COMPILER_HIGHLIGHT_ON_ERROR: str
PARAM_DEPRECATE_LEVEL: str
PARAM_DUMP_INSTRUCTIONS: str
PARAM_IMPORT_PATH_PACKAGES: str
PARAM_IMPORT_PATH_SYSTEM: str
PARAM_IMPORT_PATH_USER: str
PARAM_INPUT_CHANNELS: str
PARAM_IS_REALTIME_AUDIO_HINT: str
PARAM_OTF_ENABLE: str
PARAM_OTF_PORT: str
PARAM_OTF_PRINT_WARNINGS: str
PARAM_OUTPUT_CHANNELS: str
PARAM_SAMPLE_RATE: str
PARAM_TTY_COLOR: str
PARAM_TTY_WIDTH_HINT: str
PARAM_USER_CHUGINS: str
PARAM_VERSION: str
PARAM_VM_ADAPTIVE: str
PARAM_VM_HALT: str
PARAM_WORKING_DIRECTORY: str

# Log level constants
LOG_NONE: int
LOG_CORE: int
LOG_SYSTEM: int
LOG_HERALD: int
LOG_WARNING: int
LOG_INFO: int
LOG_DEBUG: int
LOG_FINE: int
LOG_FINER: int
LOG_FINEST: int
LOG_ALL: int
